### ISSUE TITLE
Filament Tenancy / Team support

### ISSUE THREAD

**Issue by sudanese** [tomatophp/filament-settings-hub#1]
Hi there ,
thanks for the nice plugin, would it be able to configure it to support Teanancy ?
with Panel with Filament tenancy enabled, I'm getting this error 
Missing required parameter for [Route: filament.app.pages.site-settings] [URI: app/{tenant}/site-settings] [Missing parameter: tenant].

Thanks

**Comment by 3x1io** [comment]
fixed in v1.0.2 

https://github.com/tomatophp/filament-settings-hub/releases/tag/v1.0.2

**Comment by sudanese** [comment]
Thanks
