### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [heroicon-s-cog]

### ISSUE THREAD

**Issue by hussainabuhajjaj** [tomatophp/filament-settings-hub#9]
### What happened?

i face this issue after installtion

### How to reproduce the bug

once i visit the settings website i got this error

### Package Version

letast

### PHP Version

8.2

### Laravel Version

11.x

### Which operating systems does with happen with?

macOS

**Comment by 3x1io** [comment]
hi @hussainabuhajjaj can you try clearing your cache?

```bash
php artisan optimize
```

because the problem is that you can't access the Boxicon and it's native supported by FilamentPHP panel itself
